security:
    encoders:
        App\Entity\User:
            algorithm: argon2i

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            switch_user: true
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

            logout:
                path: app_logout

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 2592000

    access_control:
        # - { path: ^/profile, roles: ROLE_USER }
         - { path: ^/admin, roles: ROLE_USER }

